ai:
    platform:
        mistral:
            api_key: '%env(MISTRAL_API_KEY)%'

    agent:
        quiz_generator:
            platform: 'ai.platform.mistral'
            model: 'mistral-large-latest'
            prompt: 'Tu es un professeur. Tu dois générer des questions de quiz au format JSON.'
            
        chatbot_assistant:
            platform: 'ai.platform.mistral'
            model: 'mistral-small-latest' 
            prompt: 'Tu es un tuteur bienveillant. Aide l’élève à comprendre sans donner la réponse directement.'

            